title: <p align="center"> Naveen Kumar J </p>
logo: /assets/img/LJMUwithoutbackground.jpg

description:
  <p align="center">|
  <a href="https://www.linkedin.com/in/Naveenharry03/">LinkedIn</a> |
  <a href="https://github.com/Naveenharry03">GitHub</a>
 
  <table>
    <tr>
      <th>Age</th>
      <td>28</td>
    </tr>
     <tr>
      <th>Experience</th>
      <td> 7+ Years </td>      
    </tr>
    <tr>
      <th>Company Name</th>
      <td>FeFundinfo </td>      
    </tr>
    <tr>
      <th> Education </th>
      <td> Msc AI & ML , B.E (Ece) </td>
    </tr>
    <tr>
      <th> University </th>
      <td> LJMU (UK) </td>
    </tr>
    <tr>
      <th>Job Role</th>
      <td> SQAE </td>      
    </tr>
     <tr>
      <th>Location</th>
      <td>Chennai </td>
    </tr> 
      <tr>
      <th>Email Id</th>
      <td> naveenharry03@gmail.com </td>      
    </tr>
      <tr>
      <th> Contact </th>
      <td> 8754583104 </td>      
    </tr> 
  </table>


theme: jekyll-theme-minimal
