title: <p align="center"> Naveen Kumar J </p>
logo: /assets/img/LJMUwithoutbackground.jpg

description:
  <p align="center">|
  <a href="https://www.linkedin.com/in/Naveenharry03/">LinkedIn</a> |
  <a href="https://github.com/Naveenharry03">GitHub</a>
 
  <table>
    <tr>
      <th>Age</th>
      <td>28</td>
    </tr>
    <tr>
      <th>Location</th>
      <td>Chennai </td>
    </tr>
    <tr>
      <th>Education Details</th>
      <td>Msc AI & ML , B.E ECE </td>
    </tr>
    <tr>
      <th>Graduated At</th>
      <td>John Moores Liverpool University </td>
    </tr>
    <tr>
      <th>Current Job Role</th>
      <td>Senior Quality Assurance Engineer </td>      
    </tr>
      <tr>
      <th>Company Name</th>
      <td>FeFundinfo </td>      
    </tr>
      <tr>
      <th>Experience</th>
      <td> 7+ Years </td>      
    </tr>
      <tr>
      <th>Company Domain</th>
      <td>Finance </td>      
    </tr>
      <tr>
      <th>Work Mode</th>
      <td>Hybrid or Remote </td>      
    </tr>
      <tr>
      <th>Email Id</th>
      <td>naveenharry03@gmail.com </td>      
    </tr>
        </tr>
      <tr>
      <th>Contact No</th>
      <td> 8754583104 </td>      
    </tr>
        </tr>
      <tr>
      <th>Email Id</th>
      <td>naveenharry03@gmail.com </td>      
    </tr>    
  </table>


theme: jekyll-theme-minimal
