title: <p align="center"> Naveen Kumar </p>
logo: /assets/img/LJMUwithoutbackground.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/Naveenharry03/">LinkedIn</a> |
  <a href="https://github.com/Naveenharry03">GitHub</a>
 
  <br>  
  I'm working on Quality Assurance engineer in fefundinfo.
  having 6 years experience in Test autonation and Finance Domain
  Done Microsoft Azure and AI Fundamentals Certifications
  <br>
  </p>



theme: jekyll-theme-minimal
